version: '3.8'

services:
  server:
    build:
      context: backend/
    ports:
      - "8000:8000"
    volumes:
      - programs-data:/app/media/programs
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=dev-database
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db-password

volumes:
  db-data:
  programs-data:

secrets:
  db-password:
    file: backend/db/password.txt
