services:
  - type: web
    plan: free
    name: backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
